
export const url = "https://elbhkwxzteqxeqfsurrz.supabase.co"  ;
export const public_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsYmhrd3h6dGVxeGVxZnN1cnJ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzMzkwNTMsImV4cCI6MjA3MDkxNTA1M30.RKO-HfMtZpailoVgBa3ohEyB1VPjTlNTZwVi9_V57nI" ; 